import { promises as dns } from "dns";

// ---------------------------------------------------------------------------
// Blocked / Disposable domain list
// These domains are rejected on registration. This is a curated static list;
// it does not expose which specific check triggered the rejection to the client.
// ---------------------------------------------------------------------------
const BLOCKED_DOMAINS = new Set([
  // Obvious test/example domains
  "test.com",
  "abc.com",
  "example.com",
  "sample.com",
  "invalid.com",
  "fake.com",
  "noemail.com",
  "nomail.com",
  "none.com",
  "null.com",
  "placeholder.com",
  "domain.com",
  "email.com",
  "mail.com",
  "user.com",
  "localhost",
  // Well-known disposable providers
  "mailinator.com",
  "guerrillamail.com",
  "guerrillamail.info",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamail.net",
  "guerrillamail.org",
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.org",
  "tempmail.com",
  "tempmail.net",
  "tempmail.org",
  "throwam.com",
  "throwam.net",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "sharklasers.com",
  "guerrillamailblock.com",
  "grr.la",
  "dispostable.com",
  "trashmail.com",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.at",
  "trashmail.io",
  "maildrop.cc",
  "fakeinbox.com",
  "getairmail.com",
  "mailnull.com",
  "spamgourmet.com",
  "spamgourmet.org",
  "spamgourmet.net",
  "spamgourmet.me",
  "mailnesia.com",
  "mailnull.com",
  "inboxbear.com",
  "spamevader.com",
  "spammotel.com",
  "spamfree24.org",
  "spamfree24.de",
  "spamfree24.eu",
  "throwam.com",
  "throwam.net",
  "throwam.org",
  "spambox.us",
  "spam4.me",
  "spamavert.com",
  "spamgob.com",
  "antispam24.de",
  "0-mail.com",
  "0815.ru",
  "0clickemail.com",
  "0wnd.net",
  "0wnd.org",
  "20minutemail.com",
  "20mail.it",
  "33mail.com",
  "anonymbox.com",
  "anonaddy.com",
  "anonbox.net",
  "binkmail.com",
  "boun.cr",
  "bouncr.com",
  "bugmenot.com",
  "burnermail.io",
  "byom.de",
  "cellurl.com",
  "cheatmail.de",
  "cool.fr.nf",
  "courriel.fr.nf",
  "curryworld.de",
  "cust.in",
  "cuvox.de",
  "dacoolest.com",
  "dandikmail.com",
  "dayrep.com",
  "dcemail.com",
  "deadaddress.com",
  "despam.it",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "disposablemail.es",
  "disposableaddress.com",
  "dodgit.com",
  "dodgit.org",
  "doiea.com",
  "dontreg.com",
  "drdrb.net",
  "drdrb.com",
  "dump-email.info",
  "dumpmail.de",
  "dumpyemail.com",
  "duskmail.com",
  "e4ward.com",
  "egxmail.com",
  "email-fake.com",
  "email-jetable.fr",
  "email60.com",
  "emailias.com",
  "emailinfive.com",
  "emailisvalid.com",
  "emailjo.de",
  "emailsensei.com",
  "emailtemporanea.net",
  "emailtemporario.com.br",
  "emailthe.net",
  "emailtmp.com",
  "emailwarden.com",
  "emailx.at.hm",
  "emkei.cz",
  "ephemail.net",
  "etranquil.net",
  "etranquil.org",
  "etranquil.com",
  "explodemail.com",
  "eyepaste.com",
  "fake-box.com",
  "fakeemail.de",
  "fakeemails.net",
  "fakeinbox.org",
  "fakemailz.com",
  "filzmail.com",
  "flurred.com",
  "flyspam.com",
  "fr33mail.info",
  "frapmail.com",
  "freeinbox.email",
  "freemail.ms",
  "fuckingduh.com",
  "fudgerub.com",
  "garbagemail.org",
  "getairmail.cf",
  "getairmail.ga",
  "getairmail.gq",
  "getairmail.ml",
  "getairmail.tk",
  "getnada.com",
  "getonemail.com",
  "getonemail.net",
  "gishpuppy.com",
  "givmail.com",
  "gorillaswithdirtyarmpits.com",
  "gotmail.net",
  "gotmail.org",
  "gowikibooks.com",
  "gowikicampus.com",
  "gowikicars.com",
  "gowikifilms.com",
  "gowikigames.com",
  "gowikimusic.com",
  "gowikinetwork.com",
  "gowikitravel.com",
  "gowikitv.com",
  "grandmasmail.com",
  "grandmamail.com",
  "grr.la",
  "gsrv.co.uk",
  "gustr.com",
  "h.mintemail.com",
  "h8s.org",
  "hatespam.org",
  "herp.in",
  "hidemail.de",
  "hidzz.com",
  "hmamail.com",
  "hopemail.biz",
  "hulapla.de",
  "ieatspam.eu",
  "ieatspam.info",
  "ieh-mail.de",
  "ikbenspamvrij.nl",
  "imails.info",
  "inapplicable.org",
  "inboxalias.com",
  "inboxclean.com",
  "inboxclean.org",
  "inoutmail.de",
  "inoutmail.eu",
  "inoutmail.info",
  "inoutmail.net",
  "insorg-mail.info",
  "instant-mail.de",
  "ip6.li",
  "ipoo.org",
  "irish2me.com",
  "iwi.net",
  "jetable.com",
  "jetable.fr.nf",
  "jetable.net",
  "jetable.org",
  "jnxjn.com",
  "jojomail.com",
  "junk1.tk",
  "junkmail.ga",
  "junkmail.gq",
  "kazakfood.com",
  "keepmymail.com",
  "killmail.com",
  "killmail.net",
  "klassmaster.com",
  "klassmaster.net",
  "kloap.com",
  "kurzepost.de",
  "lawlita.com",
  "letthemeatspam.com",
  "lhsdv.com",
  "lifebyfood.com",
  "link2mail.net",
  "litedrop.com",
  "lol.ovpn.to",
  "lolfreak.net",
  "lookugly.com",
  "lortemail.dk",
  "lr78.com",
  "lroid.com",
  "lukop.dk",
  "m21.cc",
  "mail-filter.com",
  "mail-temporaire.fr",
  "mail.by",
  "mail1a.de",
  "mail21.cc",
  "mail2rss.org",
  "mail333.com",
  "mailbidon.com",
  "mailbiz.biz",
  "mailblocks.com",
  "mailbucket.org",
  "mailcat.biz",
  "mailcatch.com",
  "mailde.de",
  "mailde.info",
  "maildrop.cf",
  "maildrop.ga",
  "maildrop.gq",
  "maildrop.ml",
  "maildrop.tk",
  "mailexpire.com",
  "mailf5.com",
  "mailforspam.com",
  "mailfreeonline.com",
  "mailguard.me",
  "mailin8r.com",
  "mailinater.com",
  "mailismagic.com",
  "mailme.ir",
  "mailme.lv",
  "mailme24.com",
  "mailmetrash.com",
  "mailmoat.com",
  "mailms.com",
  "mailnew.com",
  "mailnew.com",
  "mailorg.org",
  "mailpick.biz",
  "mailproxsy.com",
  "mailquack.com",
  "mailrock.biz",
  "mailsac.com",
  "mailscrap.com",
  "mailshell.com",
  "mailsiphon.com",
  "mailslapping.com",
  "mailslite.com",
  "mailspeed.ru",
  "mailt.net",
  "mailtemporaire.com",
  "mailtemporaire.fr",
  "mailtome.de",
  "mailtothis.com",
  "mailtrash.net",
  "mailtv.net",
  "mailtv.tv",
  "mailwei.com",
  "mailwithyou.com",
  "mailzilla.com",
  "makemetheking.com",
  "manybrain.com",
  "mbx.cc",
  "mega.zik.dj",
  "meinspamschutz.de",
  "meltmail.com",
  "messagebeamer.de",
  "mezimages.net",
  "ministry-of-silly-walks.de",
  "mintemail.com",
  "misterpinball.de",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "msa.minemail.com",
  "mt2009.com",
  "mt2014.com",
  "myalias.pw",
  "mycleaninbox.net",
  "myemailboxy.com",
  "mymail-in.net",
  "mymailoasis.com",
  "mynetstore.de",
  "mypacks.net",
  "mypad.com",
  "mypartyclip.de",
  "myphantomemail.com",
  "mysamp.de",
  "myspaceinc.com",
  "myspaceinc.net",
  "myspaceinc.org",
  "myspacepimpedup.com",
  "myspamless.com",
  "mytempemail.com",
  "mytempmail.com",
  "mytrashmail.com",
  "nabuma.com",
  "neomailbox.com",
  "nepwk.com",
  "nervmich.net",
  "nervtmich.net",
  "netviewer-france.com",
  "neutralize.it",
  "newbpotato.tk",
  "no-spam.ws",
  "noblepioneer.com",
  "nogmailspam.info",
  "nomail.pw",
  "nomail.xl.cx",
  "nomail2me.com",
  "nomorespamemails.com",
  "nospam.ze.tc",
  "nospam4.us",
  "nospamfor.us",
  "nospammail.net",
  "notmailinator.com",
  "nowhere.org",
  "nowmymail.com",
  "nwldx.com",
  "objectmail.com",
  "obobbo.com",
  "odaymail.com",
  "oneoffemail.com",
  "oneoffmail.com",
  "onewaymail.com",
  "online.ms",
  "onlineidea.info",
  "oopi.org",
  "ordinaryamerican.net",
  "otherinbox.comuv.com",
  "ourpreviewdomain.com",
  "outlookpro.net",
  "ovpn.to",
  "owlpic.com",
  "pecinan.com",
  "pecinan.net",
  "pecinan.org",
  "pepbot.com",
  "pfui.ru",
  "pimpedupmyspace.com",
  "pjjkp.com",
  "plexolan.de",
  "poczta.onet.pl",
  "politikerclub.de",
  "poofy.org",
  "pookmail.com",
  "postacin.com",
  "privacy.net",
  "privatdemail.net",
  "proxymail.eu",
  "prtnx.com",
  "punkass.com",
  "put2.net",
  "putthisinyourspamdatabase.com",
  "quickinbox.com",
  "rcpt.at",
  "reallymymail.com",
  "receivemail.org",
  "recode.me",
  "recursor.net",
  "regbypass.comuv.com",
  "rejo.technology",
  "reliable-mail.com",
  "remail.cf",
  "remail.ga",
  "rhyta.com",
  "rklips.com",
  "rmqkr.net",
  "royal.net",
  "rtrtr.com",
  "s0ny.net",
  "safe-mail.net",
  "safetymail.info",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "selfdestructingmail.com",
  "sendspamhere.com",
  "services391.com",
  "sharedmailbox.org",
  "sharedmailbox.com",
  "shieldemail.com",
  "shiftmail.com",
  "shitmail.me",
  "shitmail.org",
  "shortmail.net",
  "sibmail.com",
  "skeefmail.com",
  "slapsfromlastnight.com",
  "slaskpost.se",
  "slipry.net",
  "slo.net",
  "slowslow.de",
  "smellfear.com",
  "smwg.info",
  "sneakemail.com",
  "snkmail.com",
  "sofimail.com",
  "sofort-mail.de",
  "sogetthis.com",
  "soodonims.com",
  "spam.la",
  "spam.mn",
  "spam.su",
  "spam4.me",
  "spamavert.com",
  "spambob.com",
  "spambob.net",
  "spambob.org",
  "spambotshere.com",
  "spamcon.org",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamcowboy.net",
  "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree24.org",
  "spamgoes.in",
  "spamherelots.com",
  "spamhereplease.com",
  "spamhole.com",
  "spamify.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com",
  "spaml.de",
  "spammotel.com",
  "spammy.host",
  "spamnot.com",
  "spamoff.de",
  "spamslicer.com",
  "spamspot.com",
  "spamstack.net",
  "spamthis.co.uk",
  "spamthisplease.com",
  "spamtrail.com",
  "speed.1s.fr",
  "spoofmail.de",
  "stuffmail.de",
  "super-auswahl.de",
  "supergreatmail.com",
  "supermailer.jp",
  "superrito.com",
  "superstachel.de",
  "suremail.info",
  "sweetxxx.de",
  "tafmail.com",
  "tagyourself.com",
  "talkinator.com",
  "techemail.com",
  "telecomix.pl",
  "temp-mail.org",
  "temp-mail.ru",
  "temp-mail.io",
  "temp.emeraldwebmail.com",
  "temp.headstrong.de",
  "tempail.com",
  "tempalias.com",
  "tempe-mail.com",
  "tempemail.biz",
  "tempemail.co.za",
  "tempemail.com",
  "tempemail.net",
  "tempimbox.com",
  "tempinbox.co.uk",
  "tempinbox.com",
  "tempmail.de",
  "tempmail.eu",
  "tempmail.it",
  "tempmailer.com",
  "tempmailer.de",
  "tempomail.fr",
  "temporarioemail.com.br",
  "temporaryemail.net",
  "temporaryemail.us",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymailaddress.com",
  "tempsky.com",
  "tempthe.net",
  "tempymail.com",
  "thanksnospam.info",
  "thc.st",
  "thelimestones.com",
  "thisisnotmyrealemail.com",
  "throwam.com",
  "throwaway.email",
  "throwmail.com",
  "tilien.com",
  "tittbit.in",
  "tizi.com",
  "tmailinator.com",
  "toiea.com",
  "tradermail.info",
  "trash-amil.com",
  "trash-mail.at",
  "trash-mail.cf",
  "trash-mail.com",
  "trash-mail.ga",
  "trash-mail.gq",
  "trash-mail.io",
  "trash-mail.me",
  "trash-mail.ml",
  "trash-mail.net",
  "trash-mail.tk",
  "trash2009.com",
  "trash2010.com",
  "trash2011.com",
  "trashdevil.com",
  "trashdevil.de",
  "trashmail.at",
  "trashmail.io",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.xyz",
  "trashmailer.com",
  "trashmail.fr",
  "trashmail.ws",
  "trillianpro.com",
  "trjam.com",
  "ttt.paname.io",
  "turual.com",
  "twinmail.de",
  "tznw.tk",
  "uggsrock.com",
  "umail.net",
  "upliftnow.com",
  "uplipht.com",
  "uroid.com",
  "us.af",
  "veryrealemail.com",
  "vfemails.com",
  "viditag.com",
  "viralplays.com",
  "vkcode.ru",
  "vlmail.com",
  "vomoto.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",
  "wasteland.rfc822.org",
  "webemail.me",
  "wee.my",
  "weg-werf-email.de",
  "wegwerf-email-addressen.de",
  "wegwerfadresse.de",
  "wegwerfemail.com",
  "wegwerfemail.de",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wetrainbayarea.com",
  "wetrainbayarea.org",
  "wh4f.org",
  "whyspam.me",
  "wickmail.net",
  "wilemail.com",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "winemaven.info",
  "wronghead.com",
  "wuzup.net",
  "wuzupmail.net",
  "www.e4ward.com",
  "wwwnew.eu",
  "x.ip6.li",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xmaily.com",
  "xoxy.net",
  "xww.ro",
  "xyzfree.net",
  "yapped.net",
  "yeah.net",
  "yep.it",
  "yogamaven.com",
  "yomail.info",
  "youmail.ga",
  "yourdomain.com",
  "ypmail.webarnak.fr.eu.org",
  "yuurok.com",
  "z1p.biz",
  "za.com",
  "zehnminuten.de",
  "zehnminutenmail.de",
  "zippymail.info",
  "zoemail.net",
  "zoemail.org",
  "zomg.info",
  "zvvzuv.com",
]);

// ---------------------------------------------------------------------------
// Validation result
// ---------------------------------------------------------------------------
export interface EmailValidationResult {
  valid: boolean;
  /** Internal reason — never exposed to the client verbatim */
  reason?: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Basic RFC-like format check */
const EMAIL_REGEX =
  /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\.[a-zA-Z]{2,}$/;

function normalizeEmail(email: string): string {
  return email.trim().toLowerCase();
}

function extractDomain(email: string): string {
  return email.split("@")[1]?.toLowerCase() ?? "";
}

function isFormatValid(email: string): boolean {
  return EMAIL_REGEX.test(email);
}

function isBlockedDomain(domain: string): boolean {
  return BLOCKED_DOMAINS.has(domain);
}

/** DNS MX lookup — returns true if the domain has at least one MX record */
async function hasMxRecord(domain: string): Promise<boolean> {
  try {
    const records = await dns.resolveMx(domain);
    return records.length > 0;
  } catch {
    // ENOTFOUND, ENODATA, ETIMEOUT etc — domain does not exist or has no MX
    return false;
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Full email validation for REGISTRATION:
 *  1. Format check
 *  2. Blocked/disposable domain check
 *  3. DNS MX record lookup
 *
 * This is intentionally async (DNS call). Do not use on login for performance.
 */
export async function validateEmailForRegistration(
  rawEmail: string
): Promise<EmailValidationResult> {
  const email = normalizeEmail(rawEmail);

  if (!isFormatValid(email)) {
    return { valid: false, reason: "invalid_format" };
  }

  const domain = extractDomain(email);
  if (!domain) {
    return { valid: false, reason: "no_domain" };
  }

  if (isBlockedDomain(domain)) {
    return { valid: false, reason: "blocked_domain" };
  }

  const mxExists = await hasMxRecord(domain);
  if (!mxExists) {
    return { valid: false, reason: "no_mx_record" };
  }

  return { valid: true };
}

/**
 * Fast email validation for LOGIN:
 *  1. Format check
 *  2. Blocked/disposable domain check
 *
 * Skips MX lookup to avoid adding latency to every login request.
 */
export function validateEmailForLogin(rawEmail: string): EmailValidationResult {
  const email = normalizeEmail(rawEmail);

  if (!isFormatValid(email)) {
    return { valid: false, reason: "invalid_format" };
  }

  const domain = extractDomain(email);
  if (!domain) {
    return { valid: false, reason: "no_domain" };
  }

  if (isBlockedDomain(domain)) {
    return { valid: false, reason: "blocked_domain" };
  }

  return { valid: true };
}

/**
 * Normalize an email address: trim + lowercase.
 * Use this to canonicalize before DB lookups.
 */
export { normalizeEmail };
